// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Domain;

#nullable disable

namespace Server.MainServer.Database.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    partial class ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Server.Domain.Entities.CoordinatorInstanceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentLaunchTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstLaunchTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMOTDEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStunEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTurnEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOnlineUsers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StunAddress")
                        .HasColumnType("TEXT");

                    b.Property<ushort?>("StunPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TurnAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("TurnPassword")
                        .HasColumnType("TEXT");

                    b.Property<ushort?>("TurnPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TurnUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CoordinatorInstances");
                });

            modelBuilder.Entity("Server.Domain.Entities.OrchestratorInstanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveSessionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectedUsersCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuLoadPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("CpuName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentLaunchTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DbProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("DnsName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstLaunchTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("GpuName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFirstLaunch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCoordinators")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDbSizeMb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOnlineUsers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryConsumption")
                        .HasColumnType("REAL");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RamSizeMb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegionCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionName")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegisteredUsersCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrchestratorInstance");
                });

            modelBuilder.Entity("Server.Domain.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoordinatorInstanceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstConnectionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastConnectionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserEntities");
                });

            modelBuilder.Entity("Server.Domain.Entities.VideoSessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedUsersCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordinatorInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("HostPeerId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VideoSessionsEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
